# Generated by Django 4.0.4 on 2022-04-22 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_category_remove_product_promotion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
