# Generated by Django 4.0.4 on 2022-04-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_delete_category_delete_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_updated',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='This is the description.', max_length=100),
        ),
    ]
